name: emv_qr_builder
description: A lightweight, pure Dart library for generating EMVCo Compliant QR Code payloads. Support VietQR (NapAS).
version: 1.0.0
repository: https://github.com/Cat1m/emv_qr_builder

environment:
  sdk: ^3.10.1

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0
